language: java

jdk:
 - openjdk11
 - oraclejdk11

env:
  global:
    - secure: "oGkueLFwywOD8QOtHDwjxHN0K1/BE6xmRzsoncdmQnAfp2dVrtRzgB1LN7WJ7YmXk0AFDR3GptRxAs32LJX9AAOeWlrHNpKsFZGwZkpsHtB+KnT4iMMrW0cxxGR0roVIB1yPZSvJCSptoAvPuroXsGnUzTd7FXP8OvN9vqBsWMise2A+TDVbgwhzGt/xOI9i15yLT9fX/TNYgD3esd0DQm7ezxTiftg3KgnL2QhBLHZdKOKC/trDwffksytzDHCIj8eR3pUkvYcet9v0v68b45+XsP80wcmT74MPX/ofOWngoNl2qFOV55Y4li9lO+cDP0ZiIJTDqPVmtpc02Xhdv57urDsyoxDOigo97x2oIrtM+LfzswHN2k4D+iZZYtCfyH5c2PEOb2qWgci9dxxjXZ8qwiqqlK9ydyKUEbMIqFA/RvJ1kWsjRss4N5FwUcivcgjx/VnEvIMh1f6Al3FF25F6HEQwH+5qjCGzYAHHhdvSaaaPnzStHafgcIqIZKDlLrEEpQNPb9iPkIPeXwhUgWfo8WyC1Z4zzJtrT9G9waJClUpHTi1E6jTfVhOS4jIfMAs0/ejNS1jdr1LRqI3TsxS0U8aL5dT58wTlzMlUbfMuz3DJHLuf8FrVZeMtB8W3jd4uSjos0GzKKP3EDjhCDKGHSactRx8+VMK0zY+x5XM="
    - # ^^ OSSRH_JIRA_USERNAME
    - secure: "FT0qnAbLKO9jypDrLVtxxN5l+I5YiL3qRsKaMadaQgl5cmO6b8ZWtZZqQvJ7IlEvnYTa2GV8WtyxEJcTr+y+p4vKGOpmOhEeXW6Mv2umNFMNf8BLnLLF6Kk1rZCdaXV20WzZT9TiW+r1pPQENfS9wJS42cIIoo7336tQuAxxyzXsNi0Uo6jlEZhs12fU43c+YoqVDH5Z/Q0KcnlOZv9S9xYYn+59BnOZJoNab5D4t7ee8k1bK2VMclxDebqd9K1lTVvRPSG08jTYLlvLa55IAvYyqEImxPhrtzz3F76J4yidbH1Gu9WthgcLg6sT4TR509oWnOmETh5I44Lus55N3LsUfv3kCAGx9pSH/GxCiKRkMja25zqzflqJs6AwB7a4EezieyewGYr0yC1kv1HZ1aRN7v6rau+My80mpTQ7rO6dyACm+ljRrjc7b4QuNz+2TvM2WPeLTZFpyQuCzHctFYfD+iQIl8gPqTSRoitObLfOWxypbLl+MBExL5Gu5wCw/gEijBunD0DXFiMLfIWQ16VNvyP9WWx62HnC2CrdIa94IsZlisWWuWVX+PBOrVcEkxjbGR+AX4vF4G5qmtFZwlP6EZpdVUH0bKB/z9pqHJRAPK4eynb+4j9qBOBiKIy8FjU4EPyqiLxiTSPEoA8JTV2lgdExI6ud/NSPi0CKqGI="
    - # ^^ OSSRH_JIRA_PASSWORD
    - secure: "iPjDyqrY387CjZ0Ey6IhVa+lIsuqVjb65TuuETphcm7UcPlqW+u64rZODMMy3gSPQqwtmhXKU7a4TcD0m5e5MHNSszEM89zJCBdwMT0qxzoZqLMN7N5ubPTbJdMtOY/jna/Lti+zPEfbGCae+o/w92+1t0cEQB/Xvkp1txcQVTlvXG8tcLskm6FmDsqI+8YgAQ0GDreyIKix2KU91B/8a1eboWeeU7/i5838LCKf4BCEg0twjSC0pUNEUIKIDyPK/I+/cH97CePlKxCwz2nQJ2ACRwyouQ8GVpsA3I7wOjkpxKJlFZPLjCDMx21IudkJrI3AfmbLxxzqyWJRLF0LlLLO+rn/4XjMuk1bua9tIedwjw4WKeGKGkHZSPKwNGqlLKyF/t08YfJOJ/mHWTkZEacf4q/LTcLssfHCDZNtE2zZ4UsnKryI+rW/TPAOjxFN8Y9G8MlK7dbfMtMlXmryzXd8pfQT/8Y0zlPUJtECbNVaX4JxKBcyEpeBU3Rh/NyyrQWS1inVFMSxeQGBHHpuZ1TUB6iqyEu6Hp/SaTwlaTYXZN5vEya1NvBeoG8wlUHecGSFg+CP5FgmLDfUZDVCAkoledox0FjOuu8u8uDi3d3lEXJMAR74841G1GyDsl/eUFJj8thdAfaWuPcij0LJamou6eA0ZrHdKbJDdnkMubI="
    - # ^^ GPG_KEY_NAME
    - secure: "qwfP7vgM9CicZ8Op/uLSexEjv0g6qquFN3rYr5fmNNu/2t5ZKkYHFWYiVRiXZbtH8JjkjJur7mdacAHZld9vUqOqmRb/+0pa2u2mLVP/WwrYfqr56RhInxyoUfiNdDYutTAAiOgbQEuH9C/OTT3FQstSfsKQdIpScGFVR913lVnluk5ZdLdbqMyAvhU14W1Ql+ePhRNGWipk15HwJLOP8AYJ/LBqCxuHUE3x6a0IU8kEWqLk7bwGZWqqR0T8huNC7L35yrd5n0pH2BDSq+G/jdEswe4UEotG8T42BF0jDDuorkv3tfr8o2W1k9N50YIV/mM7rhu03LBQXt+LnFFWCEkVYV8C/VsCLu57P49zZwbyPZueTsRZx63S4wsqmqcQiEum2vT9KhLWd5dhGsjZqE28Q+earxfMoDk1tx6e+F6djNeKo+CwqKB2Eklk3/hai++T1GudoyLQgqa+t/B5bJBiMV6O/p/BgeXXwfTEb5E1N/jd4KW9dqhjZA4+qasczAggg0MhtyUS1vh9HmOmx+1CUBF1CWZbABPz01/uauFRea3y56hptJR4WMMfMBIGujUhRcbvW6z7ztagbqE+Bwug1WXZvTFUyUPcOhkIn7QQl3bQJyceLdNhHuBVRXzb8mzmg0hGqZ69o8puc1QRRnuc0J7sPiFLSVx+EV2xjKs="
    - # ^^ GPG_PASSPHRASE

cache:
  directories:
    - ~/.m2/repository
    - ~/.sonar/cache

install: true

script: mvn -B -V clean verify sonar:sonar

deploy:
  provider: script
  script:
  - openssl aes-256-cbc -K $encrypted_2fa22c1a3c47_key -iv $encrypted_2fa22c1a3c47_iv -in ci-cd/signingkey.asc.enc -out ci-cd/signingkey.asc -d &&
    gpg --fast-import ci-cd/signingkey.asc &&
    mvn deploy -B -V -P release -DskipTests=true --settings ci-cd/mvnsettings.xml
  on:
    all_branches: true
    condition: -n "$TRAVIS_TAG" || "$TRAVIS_BRANCH" == "master"
    jdk: openjdk11


addons:
  sonarcloud:
    organization: "indvd00m"
    token:
      secure: "pMDAwVY0SYZEZJzwa5nEupXAQ5C7fWleXiRO1BolbfZw2lBLmvtJBxydF8moM+lI6X4GSOwuTAC1ruiTncypirlI+3lDz4H0VctzxHquYMHtGwtzD4HPLN8ZRNmeCpBDNUc9jPs1QHtKtFhqE5varkv8yVn8hQZU/KzGQsjfzDbDY46Nkt8a+IXRUImCumK7EF1S9b7O+of/XilubU5WLGComjhKcOYK1VbFL27cm7ihVxKqNtJohVbkBcGk9j+YAadqHQv/e969VZd7jkKbGDYtmvRziXP1iVH90gYu49DrnSRomEU16HoAwVgOQ9HZ4K/rqdzN34sHfoHqJOJeRH3MUirgFA72RtYxr78jioWxZIrpINAldx6uL44lYtmfx3QmSl1SPXIsn62dTlrYEEPJF8r+zbVwYOUh1SCzxmLlpd/RSh+RqAZl56SV1ZQJafVRPJWnYFMbLpuEXPFtPRyuk0zwBJ2IUN9wfdLxtWR89dc7qNOknp9d4LcFu1Eaz3R0PmKV2TD6Xz7CEmVAtvZqug5puOOuZv5vHWOKkIoXpwkXKjrQjAbeZSqVle0QrhTUXq9CTWAVdVeDxWQRQSyUpvRS37kK7vAFVEzyaHWjtPwf3UHEcvwfBlflxCMESNjf7l3TOX+M/c+LUruyPmLC4e39yqb8FKOMKbcwm+o="
